[package]
name = "shinigami_compiler"
version = "0.1.0"
edition = "2024_07"

[dependencies]
shinigami_engine = { path = "../engine" }
shinigami_utils = { path = "../utils" }

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = "0.31.0"

[scripts]
lint = "scarb fmt"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
