[package]
name = "shinigami_compiler"
version = "0.1.0"
edition = "2024_07"

[dependencies]
shinigami_engine = { path = "../engine" }
shinigami_utils = { path = "../utils" }

[dev-dependencies]
cairo_test.workspace = true

[scripts]
lint = "scarb fmt"
