name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo gem install mdl
          mdl -s .github/linter/readme_style.rb README.md
          mdl -s .github/linter/base_style.rb .github

  cairo-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run cargo install cairo-lint
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: scarb-cairo-lint --git https://github.com/keep-starknet-strange/cairo-lint

      - uses: asdf-vm/actions/install@v3
      - run: scarb cairo-lint
      - run: scarb cairo-lint --fix

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scarb test
